/* 
 * Salestream API
 *
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing LeadApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LeadApiTests
    {
        private LeadApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LeadApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LeadApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LeadApi
            //Assert.IsInstanceOfType(typeof(LeadApi), instance, "instance is a LeadApi");
        }

        
        /// <summary>
        /// Test LeadIdGet
        /// </summary>
        [Test]
        public void LeadIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.LeadIdGet(id);
            
        }
        
        /// <summary>
        /// Test LeadIdPut
        /// </summary>
        [Test]
        public void LeadIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string company = null;
            //string url = null;
            //string description = null;
            //List<CreateLeadContacts> contacts = null;
            //List<CreateLeadAddresses> addresses = null;
            //Object customFields = null;
            //string status = null;
            //var response = instance.LeadIdPut(id, company, url, description, contacts, addresses, customFields, status);
            //Assert.IsInstanceOf<SuccessResponse> (response, "response is SuccessResponse");
        }
        
        /// <summary>
        /// Test LeadPost
        /// </summary>
        [Test]
        public void LeadPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string company = null;
            //string url = null;
            //string description = null;
            //List<CreateLeadContacts> contacts = null;
            //List<CreateLeadAddresses> addresses = null;
            //Object customFields = null;
            //string status = null;
            //var response = instance.LeadPost(company, url, description, contacts, addresses, customFields, status);
            //Assert.IsInstanceOf<SuccessResponse> (response, "response is SuccessResponse");
        }
        
        /// <summary>
        /// Test LeadSearchPost
        /// </summary>
        [Test]
        public void LeadSearchPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string searchString = null;
            //List<string> columns = null;
            //instance.LeadSearchPost(searchString, columns);
            
        }
        
    }

}
