/* 
 * Salestream API
 *
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILeadOpportunityApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// get lead opportunities
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <returns>SuccessResponse</returns>
        SuccessResponse LeadIdOpportunityGet (string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// get lead opportunities
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        ApiResponse<SuccessResponse> LeadIdOpportunityGetWithHttpInfo (string id);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <returns>SuccessResponse</returns>
        SuccessResponse LeadIdOpportunityOpportunityIdDelete (string id, string opportunityId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        ApiResponse<SuccessResponse> LeadIdOpportunityOpportunityIdDeleteWithHttpInfo (string id, string opportunityId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>SuccessResponse</returns>
        SuccessResponse LeadIdOpportunityOpportunityIdPut (string id, string opportunityId, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        ApiResponse<SuccessResponse> LeadIdOpportunityOpportunityIdPutWithHttpInfo (string id, string opportunityId, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>SuccessResponse</returns>
        SuccessResponse LeadIdOpportunityPost (string id, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        ApiResponse<SuccessResponse> LeadIdOpportunityPostWithHttpInfo (string id, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// get lead opportunities
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <returns>Task of SuccessResponse</returns>
        System.Threading.Tasks.Task<SuccessResponse> LeadIdOpportunityGetAsync (string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// get lead opportunities
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SuccessResponse>> LeadIdOpportunityGetAsyncWithHttpInfo (string id);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <returns>Task of SuccessResponse</returns>
        System.Threading.Tasks.Task<SuccessResponse> LeadIdOpportunityOpportunityIdDeleteAsync (string id, string opportunityId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SuccessResponse>> LeadIdOpportunityOpportunityIdDeleteAsyncWithHttpInfo (string id, string opportunityId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>Task of SuccessResponse</returns>
        System.Threading.Tasks.Task<SuccessResponse> LeadIdOpportunityOpportunityIdPutAsync (string id, string opportunityId, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SuccessResponse>> LeadIdOpportunityOpportunityIdPutAsyncWithHttpInfo (string id, string opportunityId, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>Task of SuccessResponse</returns>
        System.Threading.Tasks.Task<SuccessResponse> LeadIdOpportunityPostAsync (string id, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create opportunity
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SuccessResponse>> LeadIdOpportunityPostAsyncWithHttpInfo (string id, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LeadOpportunityApi : ILeadOpportunityApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LeadOpportunityApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LeadOpportunityApi(String basePath)
        {
            this.Configuration = new Org.OpenAPITools.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LeadOpportunityApi"/> class
        /// </summary>
        /// <returns></returns>
        public LeadOpportunityApi()
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.Default;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LeadOpportunityApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LeadOpportunityApi(Org.OpenAPITools.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.OpenAPITools.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  get lead opportunities
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <returns>SuccessResponse</returns>
        public SuccessResponse LeadIdOpportunityGet (string id)
        {
             ApiResponse<SuccessResponse> localVarResponse = LeadIdOpportunityGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  get lead opportunities
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        public ApiResponse< SuccessResponse > LeadIdOpportunityGetWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling LeadOpportunityApi->LeadIdOpportunityGet");

            var localVarPath = "/lead/{id}/opportunity";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarHeaderParams["apiKey"] = this.Configuration.GetApiKeyWithPrefix("apiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LeadIdOpportunityGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessResponse)));
        }

        /// <summary>
        ///  get lead opportunities
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <returns>Task of SuccessResponse</returns>
        public async System.Threading.Tasks.Task<SuccessResponse> LeadIdOpportunityGetAsync (string id)
        {
             ApiResponse<SuccessResponse> localVarResponse = await LeadIdOpportunityGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  get lead opportunities
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SuccessResponse>> LeadIdOpportunityGetAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling LeadOpportunityApi->LeadIdOpportunityGet");

            var localVarPath = "/lead/{id}/opportunity";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarHeaderParams["apiKey"] = this.Configuration.GetApiKeyWithPrefix("apiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LeadIdOpportunityGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessResponse)));
        }

        /// <summary>
        ///  Update opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <returns>SuccessResponse</returns>
        public SuccessResponse LeadIdOpportunityOpportunityIdDelete (string id, string opportunityId)
        {
             ApiResponse<SuccessResponse> localVarResponse = LeadIdOpportunityOpportunityIdDeleteWithHttpInfo(id, opportunityId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Update opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        public ApiResponse< SuccessResponse > LeadIdOpportunityOpportunityIdDeleteWithHttpInfo (string id, string opportunityId)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdDelete");
            // verify the required parameter 'opportunityId' is set
            if (opportunityId == null)
                throw new ApiException(400, "Missing required parameter 'opportunityId' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdDelete");

            var localVarPath = "/lead/{id}/opportunity/{opportunityId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (opportunityId != null) localVarPathParams.Add("opportunityId", this.Configuration.ApiClient.ParameterToString(opportunityId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarHeaderParams["apiKey"] = this.Configuration.GetApiKeyWithPrefix("apiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LeadIdOpportunityOpportunityIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessResponse)));
        }

        /// <summary>
        ///  Update opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <returns>Task of SuccessResponse</returns>
        public async System.Threading.Tasks.Task<SuccessResponse> LeadIdOpportunityOpportunityIdDeleteAsync (string id, string opportunityId)
        {
             ApiResponse<SuccessResponse> localVarResponse = await LeadIdOpportunityOpportunityIdDeleteAsyncWithHttpInfo(id, opportunityId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Update opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SuccessResponse>> LeadIdOpportunityOpportunityIdDeleteAsyncWithHttpInfo (string id, string opportunityId)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdDelete");
            // verify the required parameter 'opportunityId' is set
            if (opportunityId == null)
                throw new ApiException(400, "Missing required parameter 'opportunityId' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdDelete");

            var localVarPath = "/lead/{id}/opportunity/{opportunityId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (opportunityId != null) localVarPathParams.Add("opportunityId", this.Configuration.ApiClient.ParameterToString(opportunityId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarHeaderParams["apiKey"] = this.Configuration.GetApiKeyWithPrefix("apiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LeadIdOpportunityOpportunityIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessResponse)));
        }

        /// <summary>
        ///  Update opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>SuccessResponse</returns>
        public SuccessResponse LeadIdOpportunityOpportunityIdPut (string id, string opportunityId, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null)
        {
             ApiResponse<SuccessResponse> localVarResponse = LeadIdOpportunityOpportunityIdPutWithHttpInfo(id, opportunityId, value, estCloseDate, assignee, confidence, contact, comment);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Update opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        public ApiResponse< SuccessResponse > LeadIdOpportunityOpportunityIdPutWithHttpInfo (string id, string opportunityId, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'opportunityId' is set
            if (opportunityId == null)
                throw new ApiException(400, "Missing required parameter 'opportunityId' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'estCloseDate' is set
            if (estCloseDate == null)
                throw new ApiException(400, "Missing required parameter 'estCloseDate' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'assignee' is set
            if (assignee == null)
                throw new ApiException(400, "Missing required parameter 'assignee' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'confidence' is set
            if (confidence == null)
                throw new ApiException(400, "Missing required parameter 'confidence' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");

            var localVarPath = "/lead/{id}/opportunity/{opportunityId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/x-www-form-urlencoded", 
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (opportunityId != null) localVarPathParams.Add("opportunityId", this.Configuration.ApiClient.ParameterToString(opportunityId)); // path parameter
            if (value != null) localVarFormParams.Add("value", this.Configuration.ApiClient.ParameterToString(value)); // form parameter
            if (estCloseDate != null) localVarFormParams.Add("est_close_date", this.Configuration.ApiClient.ParameterToString(estCloseDate)); // form parameter
            if (assignee != null) localVarFormParams.Add("assignee", this.Configuration.ApiClient.ParameterToString(assignee)); // form parameter
            if (confidence != null) localVarFormParams.Add("confidence", this.Configuration.ApiClient.ParameterToString(confidence)); // form parameter
            if (contact != null) localVarFormParams.Add("contact", this.Configuration.ApiClient.ParameterToString(contact)); // form parameter
            if (comment != null) localVarFormParams.Add("comment", this.Configuration.ApiClient.ParameterToString(comment)); // form parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarHeaderParams["apiKey"] = this.Configuration.GetApiKeyWithPrefix("apiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LeadIdOpportunityOpportunityIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessResponse)));
        }

        /// <summary>
        ///  Update opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>Task of SuccessResponse</returns>
        public async System.Threading.Tasks.Task<SuccessResponse> LeadIdOpportunityOpportunityIdPutAsync (string id, string opportunityId, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null)
        {
             ApiResponse<SuccessResponse> localVarResponse = await LeadIdOpportunityOpportunityIdPutAsyncWithHttpInfo(id, opportunityId, value, estCloseDate, assignee, confidence, contact, comment);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Update opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="opportunityId">opportunity id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SuccessResponse>> LeadIdOpportunityOpportunityIdPutAsyncWithHttpInfo (string id, string opportunityId, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'opportunityId' is set
            if (opportunityId == null)
                throw new ApiException(400, "Missing required parameter 'opportunityId' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'estCloseDate' is set
            if (estCloseDate == null)
                throw new ApiException(400, "Missing required parameter 'estCloseDate' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'assignee' is set
            if (assignee == null)
                throw new ApiException(400, "Missing required parameter 'assignee' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");
            // verify the required parameter 'confidence' is set
            if (confidence == null)
                throw new ApiException(400, "Missing required parameter 'confidence' when calling LeadOpportunityApi->LeadIdOpportunityOpportunityIdPut");

            var localVarPath = "/lead/{id}/opportunity/{opportunityId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/x-www-form-urlencoded", 
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (opportunityId != null) localVarPathParams.Add("opportunityId", this.Configuration.ApiClient.ParameterToString(opportunityId)); // path parameter
            if (value != null) localVarFormParams.Add("value", this.Configuration.ApiClient.ParameterToString(value)); // form parameter
            if (estCloseDate != null) localVarFormParams.Add("est_close_date", this.Configuration.ApiClient.ParameterToString(estCloseDate)); // form parameter
            if (assignee != null) localVarFormParams.Add("assignee", this.Configuration.ApiClient.ParameterToString(assignee)); // form parameter
            if (confidence != null) localVarFormParams.Add("confidence", this.Configuration.ApiClient.ParameterToString(confidence)); // form parameter
            if (contact != null) localVarFormParams.Add("contact", this.Configuration.ApiClient.ParameterToString(contact)); // form parameter
            if (comment != null) localVarFormParams.Add("comment", this.Configuration.ApiClient.ParameterToString(comment)); // form parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarHeaderParams["apiKey"] = this.Configuration.GetApiKeyWithPrefix("apiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LeadIdOpportunityOpportunityIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessResponse)));
        }

        /// <summary>
        ///  Create opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>SuccessResponse</returns>
        public SuccessResponse LeadIdOpportunityPost (string id, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null)
        {
             ApiResponse<SuccessResponse> localVarResponse = LeadIdOpportunityPostWithHttpInfo(id, value, estCloseDate, assignee, confidence, contact, comment);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Create opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        public ApiResponse< SuccessResponse > LeadIdOpportunityPostWithHttpInfo (string id, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling LeadOpportunityApi->LeadIdOpportunityPost");
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling LeadOpportunityApi->LeadIdOpportunityPost");
            // verify the required parameter 'estCloseDate' is set
            if (estCloseDate == null)
                throw new ApiException(400, "Missing required parameter 'estCloseDate' when calling LeadOpportunityApi->LeadIdOpportunityPost");
            // verify the required parameter 'assignee' is set
            if (assignee == null)
                throw new ApiException(400, "Missing required parameter 'assignee' when calling LeadOpportunityApi->LeadIdOpportunityPost");
            // verify the required parameter 'confidence' is set
            if (confidence == null)
                throw new ApiException(400, "Missing required parameter 'confidence' when calling LeadOpportunityApi->LeadIdOpportunityPost");

            var localVarPath = "/lead/{id}/opportunity";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/x-www-form-urlencoded", 
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (value != null) localVarFormParams.Add("value", this.Configuration.ApiClient.ParameterToString(value)); // form parameter
            if (estCloseDate != null) localVarFormParams.Add("est_close_date", this.Configuration.ApiClient.ParameterToString(estCloseDate)); // form parameter
            if (assignee != null) localVarFormParams.Add("assignee", this.Configuration.ApiClient.ParameterToString(assignee)); // form parameter
            if (confidence != null) localVarFormParams.Add("confidence", this.Configuration.ApiClient.ParameterToString(confidence)); // form parameter
            if (contact != null) localVarFormParams.Add("contact", this.Configuration.ApiClient.ParameterToString(contact)); // form parameter
            if (comment != null) localVarFormParams.Add("comment", this.Configuration.ApiClient.ParameterToString(comment)); // form parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarHeaderParams["apiKey"] = this.Configuration.GetApiKeyWithPrefix("apiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LeadIdOpportunityPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessResponse)));
        }

        /// <summary>
        ///  Create opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>Task of SuccessResponse</returns>
        public async System.Threading.Tasks.Task<SuccessResponse> LeadIdOpportunityPostAsync (string id, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null)
        {
             ApiResponse<SuccessResponse> localVarResponse = await LeadIdOpportunityPostAsyncWithHttpInfo(id, value, estCloseDate, assignee, confidence, contact, comment);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Create opportunity
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">lead id</param>
        /// <param name="value"></param>
        /// <param name="estCloseDate"></param>
        /// <param name="assignee"></param>
        /// <param name="confidence"></param>
        /// <param name="contact"> (optional)</param>
        /// <param name="comment"> (optional)</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SuccessResponse>> LeadIdOpportunityPostAsyncWithHttpInfo (string id, int? value, int? estCloseDate, string assignee, int? confidence, string contact = null, Text comment = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling LeadOpportunityApi->LeadIdOpportunityPost");
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling LeadOpportunityApi->LeadIdOpportunityPost");
            // verify the required parameter 'estCloseDate' is set
            if (estCloseDate == null)
                throw new ApiException(400, "Missing required parameter 'estCloseDate' when calling LeadOpportunityApi->LeadIdOpportunityPost");
            // verify the required parameter 'assignee' is set
            if (assignee == null)
                throw new ApiException(400, "Missing required parameter 'assignee' when calling LeadOpportunityApi->LeadIdOpportunityPost");
            // verify the required parameter 'confidence' is set
            if (confidence == null)
                throw new ApiException(400, "Missing required parameter 'confidence' when calling LeadOpportunityApi->LeadIdOpportunityPost");

            var localVarPath = "/lead/{id}/opportunity";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/x-www-form-urlencoded", 
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (value != null) localVarFormParams.Add("value", this.Configuration.ApiClient.ParameterToString(value)); // form parameter
            if (estCloseDate != null) localVarFormParams.Add("est_close_date", this.Configuration.ApiClient.ParameterToString(estCloseDate)); // form parameter
            if (assignee != null) localVarFormParams.Add("assignee", this.Configuration.ApiClient.ParameterToString(assignee)); // form parameter
            if (confidence != null) localVarFormParams.Add("confidence", this.Configuration.ApiClient.ParameterToString(confidence)); // form parameter
            if (contact != null) localVarFormParams.Add("contact", this.Configuration.ApiClient.ParameterToString(contact)); // form parameter
            if (comment != null) localVarFormParams.Add("comment", this.Configuration.ApiClient.ParameterToString(comment)); // form parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarHeaderParams["apiKey"] = this.Configuration.GetApiKeyWithPrefix("apiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LeadIdOpportunityPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessResponse)));
        }

    }
}
