/* 
 * Salestream API
 *
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CreateEmail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateEmailTests
    {
        // TODO uncomment below to declare an instance variable for CreateEmail
        //private CreateEmail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateEmail
            //instance = new CreateEmail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateEmail
        /// </summary>
        [Test]
        public void CreateEmailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateEmail
            //Assert.IsInstanceOfType<CreateEmail> (instance, "variable 'instance' is a CreateEmail");
        }


        /// <summary>
        /// Test the property 'EmailId'
        /// </summary>
        [Test]
        public void EmailIdTest()
        {
            // TODO unit test for the property 'EmailId'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Test]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }
        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Test]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Draft'
        /// </summary>
        [Test]
        public void DraftTest()
        {
            // TODO unit test for the property 'Draft'
        }
        /// <summary>
        /// Test the property 'ReminderEnabled'
        /// </summary>
        [Test]
        public void ReminderEnabledTest()
        {
            // TODO unit test for the property 'ReminderEnabled'
        }
        /// <summary>
        /// Test the property 'ReminderDate'
        /// </summary>
        [Test]
        public void ReminderDateTest()
        {
            // TODO unit test for the property 'ReminderDate'
        }
        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Test]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }

    }

}
