/* 
 * Salestream API
 *
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing UpdateSms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateSmsTests
    {
        // TODO uncomment below to declare an instance variable for UpdateSms
        //private UpdateSms instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateSms
            //instance = new UpdateSms();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateSms
        /// </summary>
        [Test]
        public void UpdateSmsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateSms
            //Assert.IsInstanceOfType<UpdateSms> (instance, "variable 'instance' is a UpdateSms");
        }


        /// <summary>
        /// Test the property 'PhoneId'
        /// </summary>
        [Test]
        public void PhoneIdTest()
        {
            // TODO unit test for the property 'PhoneId'
        }
        /// <summary>
        /// Test the property 'DetailId'
        /// </summary>
        [Test]
        public void DetailIdTest()
        {
            // TODO unit test for the property 'DetailId'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Draft'
        /// </summary>
        [Test]
        public void DraftTest()
        {
            // TODO unit test for the property 'Draft'
        }
        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Test]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }

    }

}
