/* 
 * Salestream API
 *
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing UpdateWebhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateWebhookTests
    {
        // TODO uncomment below to declare an instance variable for UpdateWebhook
        //private UpdateWebhook instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateWebhook
            //instance = new UpdateWebhook();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateWebhook
        /// </summary>
        [Test]
        public void UpdateWebhookInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateWebhook
            //Assert.IsInstanceOfType<UpdateWebhook> (instance, "variable 'instance' is a UpdateWebhook");
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'FallbackUrl'
        /// </summary>
        [Test]
        public void FallbackUrlTest()
        {
            // TODO unit test for the property 'FallbackUrl'
        }
        /// <summary>
        /// Test the property 'ErrorUrl'
        /// </summary>
        [Test]
        public void ErrorUrlTest()
        {
            // TODO unit test for the property 'ErrorUrl'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Test]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }
        /// <summary>
        /// Test the property 'RetryAttempts'
        /// </summary>
        [Test]
        public void RetryAttemptsTest()
        {
            // TODO unit test for the property 'RetryAttempts'
        }

    }

}
